aws {
  secretName = "XXXXXXX"
  region = "ap-southeast-1"
}

kafka {
  servers = "XXXXXXXXX:9096,XXXXXXXXX:9096"
  scramLoginModule = "kafkashaded.org.apache.kafka.common.security.scram.ScramLoginModule"
}

mongo {
  uri = "mongodb://X.X.X.X:27017/"
}

app {
  checkpointLocation = "/Volumes/cdip_catalog/proj_OOO_risk_center/ckpts/one_OOO_group_login_guard"
  anomalyResultTablePath = "cdip_catalog.proj_OOO_risk_center.oneOOO_stream_login_guard_anomaly_resluts"
}
