aws {
  secretName = "XXXXXXXXXX"
  region = "ap-southeast-1"
}

kafka {
  servers = "XXXXXX:9196,XXXXXXX:9196"
  scramLoginModule = "org.apache.kafka.common.security.scram.ScramLoginModule"
}

mongo {
  uri = "mongodb://X.X.X.X:27017/"
}

app {
  checkpointLocation = "./ckpt"
  anomalyResultTablePath = "./delta/oneOOO_stream_login_guard_anomaly_resluts"
}