kafka {
  startingOffsets = "earliest"
  failOnDataLoss = "true"
}

mongo {
  db = "spark"
  collection = "test"
}

app {
  streamWatermark = "0 seconds"
  streamTriggerProcessingTime = "5 seconds"
  anomalyTimeWindowSeconds = 60
  msgIgnoreTime = "30 days"
  whitelistRetentionTime = "60 minutes"
  lastRecentLoginSets = 5
  anomalousMoveTimeThreshold = "30 seconds"
  realtimeWhitelistThreshold = "2 hours"
}